export const CREATE_TOKEN = "Create Token"
export const UNIQUE_NFT = "NFT"
export const COMMON_NFT = "NFT Collection"
export const CUSTOM_NFT = "Custom Asset"
export const WEB3_TICKET = "Web3 Ticket"
export const FRACTIONAL_NFT = "Fractional NFT"
export const SECURITY = "Security"